# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
#   bundle exec jekyll serve --livereload
#
#
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Emerging Approaches for Tumor Analyses in Epidemiological Studies
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A DCEG course in tumor bioinformatics analysis for epidemiology
#baseurl: "/test-url" # the subpath of your site, e.g. /blog
baseurl: "/tumor_epidemiology_approaches"
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme
#remote_theme: just-the-docs/just-the-docs
#theme: minima
plugins:
# - jekyll-feed
favicon: favicon3.png?



# collections
collections:
  instructors:
  speakers:

# updates
paginate: 5
paginate_path: "/news/page:num"

# FORMATTING
#
#fixed_navbar: top
defaults:
  -
    scope:
      path: ""
    values:
      #hero_height: is-small
      #hero_image: /github_website/assets/Final_Artwork_Sherlock_Cover.jpeg
      hero_image: /tumor_epidemiology_approaches/assets/Final_Artwork_Sherlock_Cover-0.4.png
      hero_darken: true
  -
    scope:
      path: sessions
    values:
      hero_height: is-small
      show_menubar: true
      menubar: sessions_sidebar
  -
    scope:
      type: posts
    values:
      hero_height: is-small
      show_sidebar: true
  -
    scope:
      path: sessions/session_1
    values:
      title: "Session 1: Introduction to Computing Clusters and Bioinformatics"
      parent: sessions
      nav_order: 1
      tabs: session1_tabs
  -
    scope:
      path: sessions/session_2
    values:
      title: "Session 2: Public Databases"
      parent: sessions
      nav_order: 2
      tabs: session2_tabs
  -
    scope:
      path: sessions/session_3
    values:
      title: "Session 3: DNA Sequencing Strategies and Quality Control"
      parent: sessions
      nav_order: 3
      tabs: session3_tabs
  -
    scope:
      path: sessions/session_4
    values:
      title: "Session 4: Mutation Calling and Analysis"
      parent: sessions
      nav_order: 4
      tabs: session4_tabs
  -
    scope:
      path: sessions/session_5
    values:
      title: "Session 5: Mutational Signatures"
      parent: sessions
      nav_order: 5
      tabs: session5_tabs
  -
    scope:
      path: sessions/session_6
    values:
      title: "Session 6: Structural Variant Analysis"
      parent: sessions
      nav_order: 6
      tabs: session6_tabs
  -
    scope:
      path: sessions/session_7
    values:
      title: "Session 7: Somatic Copy Number Alterations"
      parent: sessions
      nav_order: 7
      tabs: session7_tabs
  -
    scope:
      path: sessions/session_8
    values:
      title: "Session 8: Identifying Cancer Drivers"
      parent: sessions
      nav_order: 8
      tabs: session8_tabs
  -
    scope:
      path: sessions/session_9
    values:
      title: "Session 9: Tumor Evolution"
      parent: sessions
      nav_order: 9
      tabs: session9_tabs
  -
    scope:
      path: sessions/session_10
    values:
      title: "Session 10: Transcriptome-based Study Designs"
      parent: sessions
      nav_order: 10
      tabs: session10_tabs
  -
    scope:
      path: sessions/session_11
    values:
      title: "Session 11: RNA-seq Data Mining"
      parent: sessions
      nav_order: 11
      tabs: session11_tabs
  -
    scope:
      path: sessions/session_12
    values:
      title: "Session 12: Data Visualization Approaches"
      parent: sessions
      nav_order: 12
      tabs: session12_tabs
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
